-- UP
-- Add missing columns to challenges table
ALTER TABLE challenges 
ADD COLUMN IF NOT EXISTS points INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS start_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS end_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP + INTERVAL '7 days';

-- Add missing columns to submissions table
ALTER TABLE submissions 
ADD COLUMN IF NOT EXISTS score INTEGER DEFAULT 0;

-- Add missing columns to users table
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS points INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS name VARCHAR(100),
ADD COLUMN IF NOT EXISTS college_id VARCHAR(50),
ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(255),
ADD COLUMN IF NOT EXISTS github_username VARCHAR(100),
ADD COLUMN IF NOT EXISTS linkedin_url VARCHAR(255);

-- DOWN
-- Remove added columns
ALTER TABLE challenges DROP COLUMN IF EXISTS points;
ALTER TABLE challenges DROP COLUMN IF EXISTS start_date;
ALTER TABLE challenges DROP COLUMN IF EXISTS end_date;
ALTER TABLE submissions DROP COLUMN IF EXISTS score;
ALTER TABLE users DROP COLUMN IF EXISTS points;
ALTER TABLE users DROP COLUMN IF EXISTS name;
ALTER TABLE users DROP COLUMN IF EXISTS college_id;
ALTER TABLE users DROP COLUMN IF EXISTS avatar_url;
ALTER TABLE users DROP COLUMN IF EXISTS github_username;
ALTER TABLE users DROP COLUMN IF EXISTS linkedin_url;
