# Alertmanager Configuration

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@codnite.com'
  smtp_auth_username: 'alerts@codnite.com'
  smtp_auth_password: 'your_smtp_password'

# The directory from which notification templates are read.
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# The root route on which each condition enters the routing tree.
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
    group_wait: 5s
    group_interval: 5s
    repeat_interval: 30m
  - match:
      severity: high
    receiver: 'high-alerts'
    group_wait: 10s
    group_interval: 10s
    repeat_interval: 1h
  - match:
      severity: warning
    receiver: 'warning-alerts'
    group_wait: 30s
    group_interval: 30s
    repeat_interval: 2h
  - match:
      severity: info
    receiver: 'info-alerts'
    group_wait: 1m
    group_interval: 1m
    repeat_interval: 4h

# Inhibition rules allow to mute a set of alerts given that another alert is
# firing.
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

# A list of notification receivers.
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'

- name: 'critical-alerts'
  email_configs:
  - to: 'oncall@codnite.com'
    subject: '[CRITICAL] {{ .GroupLabels.alertname }} - {{ .GroupLabels.instance }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Instance: {{ .Labels.instance }}
      Severity: {{ .Labels.severity }}
      Time: {{ .StartsAt }}
      {{ end }}
    headers:
      Subject: '[CRITICAL] Codnite Alert'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#alerts-critical'
    title: 'Critical Alert'
    text: |
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Instance:* {{ .Labels.instance }}
      *Severity:* {{ .Labels.severity }}
      *Time:* {{ .StartsAt }}
      {{ end }}
  pagerduty_configs:
  - routing_key: 'your_pagerduty_routing_key'
    description: '{{ .GroupLabels.alertname }} - {{ .GroupLabels.instance }}'
    details:
      summary: '{{ .Annotations.summary }}'
      description: '{{ .Annotations.description }}'
      instance: '{{ .Labels.instance }}'
      severity: '{{ .Labels.severity }}'

- name: 'high-alerts'
  email_configs:
  - to: 'devops@codnite.com'
    subject: '[HIGH] {{ .GroupLabels.alertname }} - {{ .GroupLabels.instance }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Instance: {{ .Labels.instance }}
      Severity: {{ .Labels.severity }}
      Time: {{ .StartsAt }}
      {{ end }}
    headers:
      Subject: '[HIGH] Codnite Alert'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#alerts-high'
    title: 'High Priority Alert'
    text: |
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Instance:* {{ .Labels.instance }}
      *Severity:* {{ .Labels.severity }}
      *Time:* {{ .StartsAt }}
      {{ end }}

- name: 'warning-alerts'
  email_configs:
  - to: 'team@codnite.com'
    subject: '[WARNING] {{ .GroupLabels.alertname }} - {{ .GroupLabels.instance }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Instance: {{ .Labels.instance }}
      Severity: {{ .Labels.severity }}
      Time: {{ .StartsAt }}
      {{ end }}
    headers:
      Subject: '[WARNING] Codnite Alert'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#alerts-warning'
    title: 'Warning Alert'
    text: |
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Instance:* {{ .Labels.instance }}
      *Severity:* {{ .Labels.severity }}
      *Time:* {{ .StartsAt }}
      {{ end }}

- name: 'info-alerts'
  email_configs:
  - to: 'info@codnite.com'
    subject: '[INFO] {{ .GroupLabels.alertname }} - {{ .GroupLabels.instance }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Instance: {{ .Labels.instance }}
      Severity: {{ .Labels.severity }}
      Time: {{ .StartsAt }}
      {{ end }}
    headers:
      Subject: '[INFO] Codnite Alert'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#alerts-info'
    title: 'Info Alert'
    text: |
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Instance:* {{ .Labels.instance }}
      *Severity:* {{ .Labels.severity }}
      *Time:* {{ .StartsAt }}
      {{ end }}

# Time intervals for which to mute notifications.
time_intervals:
  - name: 'maintenance'
    time_intervals:
      - times:
          - start_time: '02:00'
            end_time: '04:00'
        weekdays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday']
        months: ['january:december']
        years: ['2024:2030']

  - name: 'weekends'
    time_intervals:
      - weekdays: ['saturday', 'sunday']

# Mute time intervals for different severity levels
mute_time_intervals:
  - name: 'mute-warnings-weekends'
    time_intervals: ['weekends']
    severity: 'warning'

  - name: 'mute-info-maintenance'
    time_intervals: ['maintenance']
    severity: 'info'
